import { FiServer, FiDatabase, FiCloud, FiShield, FiUsers, FiGlobe, FiBox, FiCpu, FiHardDrive, FiActivity, FiMail, FiSearch, FiBell, FiTrendingUp, FiLock, FiZap, FiCode, FiUploadCloud, FiDownloadCloud, FiRefreshCw } from 'react-icons/fi';
import { SiRedis, SiMongodb, SiPostgresql, SiKubernetes, SiDocker, SiNginx, SiApachekafka, SiPrometheus, SiGrafana, SiRabbitmq, SiTensorflow, SiPytorch, SiApachespark, SiApacheairflow, SiJupyter, SiMlflow } from 'react-icons/si';
import { BiData, BiLineChart, BiBrain, BiChip } from 'react-icons/bi';
import { AiOutlineApi, AiOutlineRobot, AiOutlineCloudUpload } from 'react-icons/ai';
import { MdOutlineComputer, MdStorage, MdSecurity, MdNotifications, MdAnalytics, MdMemory, MdDataUsage } from 'react-icons/md';
import { GiArtificialIntelligence, GiBrain } from 'react-icons/gi';
import { TbBrandPython } from 'react-icons/tb';

export const nodeCategories = {
  compute: {
    label: 'Compute',
    icon: FiCpu,
    color: '#3b82f6',
  },
  storage: {
    label: 'Storage',
    icon: FiDatabase,
    color: '#10b981',
  },
  network: {
    label: 'Network',
    icon: FiGlobe,
    color: '#8b5cf6',
  },
  messaging: {
    label: 'Messaging',
    icon: FiMail,
    color: '#f59e0b',
  },
  monitoring: {
    label: 'Monitoring',
    icon: FiActivity,
    color: '#06b6d4',
  },
  security: {
    label: 'Security',
    icon: FiShield,
    color: '#ef4444',
  },
  client: {
    label: 'Client',
    icon: FiUsers,
    color: '#ec4899',
  },
  services: {
    label: 'Services',
    icon: FiCloud,
    color: '#14b8a6',
  },
  aiml: {
    label: 'AI/ML',
    icon: BiBrain,
    color: '#9333ea',
  },
  dataProcessing: {
    label: 'Data Pipeline',
    icon: BiData,
    color: '#fb923c',
  },
};

export const nodeTypes = {
  // Compute
  server: {
    id: 'server',
    label: 'Server',
    icon: FiServer,
    color: '#3b82f6',
    category: 'compute',
    description: 'Application server or web server',
  },
  microservice: {
    id: 'microservice',
    label: 'Microservice',
    icon: FiBox,
    color: '#3b82f6',
    category: 'compute',
    description: 'Microservice component',
  },
  container: {
    id: 'container',
    label: 'Container',
    icon: SiDocker,
    color: '#2496ed',
    category: 'compute',
    description: 'Docker container',
  },
  kubernetes: {
    id: 'kubernetes',
    label: 'Kubernetes',
    icon: SiKubernetes,
    color: '#326ce5',
    category: 'compute',
    description: 'Kubernetes cluster',
  },
  lambda: {
    id: 'lambda',
    label: 'Serverless',
    icon: FiZap,
    color: '#3b82f6',
    category: 'compute',
    description: 'Serverless function',
  },
  
  // Storage
  database: {
    id: 'database',
    label: 'Database',
    icon: FiDatabase,
    color: '#10b981',
    category: 'storage',
    description: 'Relational database',
  },
  mongodb: {
    id: 'mongodb',
    label: 'MongoDB',
    icon: SiMongodb,
    color: '#47a248',
    category: 'storage',
    description: 'MongoDB NoSQL database',
  },
  postgresql: {
    id: 'postgresql',
    label: 'PostgreSQL',
    icon: SiPostgresql,
    color: '#336791',
    category: 'storage',
    description: 'PostgreSQL database',
  },
  redis: {
    id: 'redis',
    label: 'Redis',
    icon: SiRedis,
    color: '#dc382d',
    category: 'storage',
    description: 'Redis cache',
  },
  cache: {
    id: 'cache',
    label: 'Cache',
    icon: FiActivity,
    color: '#10b981',
    category: 'storage',
    description: 'Caching layer',
  },
  storage: {
    id: 'storage',
    label: 'Storage',
    icon: MdStorage,
    color: '#10b981',
    category: 'storage',
    description: 'File storage or object storage',
  },
  dataWarehouse: {
    id: 'dataWarehouse',
    label: 'Data Warehouse',
    icon: BiData,
    color: '#10b981',
    category: 'storage',
    description: 'Data warehouse for analytics',
  },
  
  // Network
  loadBalancer: {
    id: 'loadBalancer',
    label: 'Load Balancer',
    icon: BiData,
    color: '#8b5cf6',
    category: 'network',
    description: 'Load balancing service',
  },
  cdn: {
    id: 'cdn',
    label: 'CDN',
    icon: FiGlobe,
    color: '#8b5cf6',
    category: 'network',
    description: 'Content delivery network',
  },
  apiGateway: {
    id: 'apiGateway',
    label: 'API Gateway',
    icon: AiOutlineApi,
    color: '#8b5cf6',
    category: 'network',
    description: 'API gateway service',
  },
  nginx: {
    id: 'nginx',
    label: 'Nginx',
    icon: SiNginx,
    color: '#009639',
    category: 'network',
    description: 'Nginx web server',
  },
  dns: {
    id: 'dns',
    label: 'DNS',
    icon: FiGlobe,
    color: '#8b5cf6',
    category: 'network',
    description: 'DNS service',
  },
  
  // Messaging
  kafka: {
    id: 'kafka',
    label: 'Kafka',
    icon: SiApachekafka,
    color: '#231f20',
    category: 'messaging',
    description: 'Apache Kafka message queue',
  },
  rabbitmq: {
    id: 'rabbitmq',
    label: 'RabbitMQ',
    icon: SiRabbitmq,
    color: '#ff6600',
    category: 'messaging',
    description: 'RabbitMQ message broker',
  },
  messageQueue: {
    id: 'messageQueue',
    label: 'Message Queue',
    icon: FiMail,
    color: '#f59e0b',
    category: 'messaging',
    description: 'Generic message queue',
  },
  eventBus: {
    id: 'eventBus',
    label: 'Event Bus',
    icon: FiZap,
    color: '#f59e0b',
    category: 'messaging',
    description: 'Event-driven message bus',
  },
  
  // Monitoring
  prometheus: {
    id: 'prometheus',
    label: 'Prometheus',
    icon: SiPrometheus,
    color: '#e6522c',
    category: 'monitoring',
    description: 'Prometheus monitoring',
  },
  grafana: {
    id: 'grafana',
    label: 'Grafana',
    icon: SiGrafana,
    color: '#f46800',
    category: 'monitoring',
    description: 'Grafana dashboards',
  },
  monitoring: {
    id: 'monitoring',
    label: 'Monitoring',
    icon: FiActivity,
    color: '#06b6d4',
    category: 'monitoring',
    description: 'Monitoring service',
  },
  logging: {
    id: 'logging',
    label: 'Logging',
    icon: BiLineChart,
    color: '#06b6d4',
    category: 'monitoring',
    description: 'Centralized logging',
  },
  analytics: {
    id: 'analytics',
    label: 'Analytics',
    icon: MdAnalytics,
    color: '#06b6d4',
    category: 'monitoring',
    description: 'Analytics platform',
  },
  
  // Security
  firewall: {
    id: 'firewall',
    label: 'Firewall',
    icon: FiShield,
    color: '#ef4444',
    category: 'security',
    description: 'Firewall security',
  },
  auth: {
    id: 'auth',
    label: 'Authentication',
    icon: MdSecurity,
    color: '#ef4444',
    category: 'security',
    description: 'Authentication service',
  },
  waf: {
    id: 'waf',
    label: 'WAF',
    icon: FiShield,
    color: '#ef4444',
    category: 'security',
    description: 'Web Application Firewall',
  },
  encryption: {
    id: 'encryption',
    label: 'Encryption',
    icon: FiLock,
    color: '#ef4444',
    category: 'security',
    description: 'Encryption service',
  },
  
  // Client
  webApp: {
    id: 'webApp',
    label: 'Web App',
    icon: MdOutlineComputer,
    color: '#ec4899',
    category: 'client',
    description: 'Web application',
  },
  mobileApp: {
    id: 'mobileApp',
    label: 'Mobile App',
    icon: FiUsers,
    color: '#ec4899',
    category: 'client',
    description: 'Mobile application',
  },
  user: {
    id: 'user',
    label: 'User',
    icon: FiUsers,
    color: '#ec4899',
    category: 'client',
    description: 'End user',
  },
  admin: {
    id: 'admin',
    label: 'Admin Panel',
    icon: FiUsers,
    color: '#ec4899',
    category: 'client',
    description: 'Admin dashboard',
  },
  
  // Services
  cloudService: {
    id: 'cloudService',
    label: 'Cloud Service',
    icon: FiCloud,
    color: '#14b8a6',
    category: 'services',
    description: 'Third-party cloud service',
  },
  aws: {
    id: 'aws',
    label: 'AWS',
    icon: FiCloud,
    color: '#ff9900',
    category: 'services',
    description: 'Amazon Web Services',
  },
  searchEngine: {
    id: 'searchEngine',
    label: 'Search',
    icon: FiSearch,
    color: '#14b8a6',
    category: 'services',
    description: 'Search engine service',
  },
  elasticsearch: {
    id: 'elasticsearch',
    label: 'Elasticsearch',
    icon: FiSearch,
    color: '#005571',
    category: 'services',
    description: 'Elasticsearch search engine',
  },
  emailService: {
    id: 'emailService',
    label: 'Email Service',
    icon: FiMail,
    color: '#14b8a6',
    category: 'services',
    description: 'Email sending service',
  },
  notification: {
    id: 'notification',
    label: 'Notifications',
    icon: FiBell,
    color: '#14b8a6',
    category: 'services',
    description: 'Push notification service',
  },
  payment: {
    id: 'payment',
    label: 'Payment',
    icon: FiTrendingUp,
    color: '#14b8a6',
    category: 'services',
    description: 'Payment gateway',
  },
  
  // AI/ML Components
  mlModel: {
    id: 'mlModel',
    label: 'ML Model',
    icon: BiBrain,
    color: '#9333ea',
    category: 'aiml',
    description: 'Machine Learning model',
  },
  tensorflow: {
    id: 'tensorflow',
    label: 'TensorFlow',
    icon: SiTensorflow,
    color: '#ff6f00',
    category: 'aiml',
    description: 'TensorFlow ML framework',
  },
  pytorch: {
    id: 'pytorch',
    label: 'PyTorch',
    icon: SiPytorch,
    color: '#ee4c2c',
    category: 'aiml',
    description: 'PyTorch ML framework',
  },
  modelServing: {
    id: 'modelServing',
    label: 'Model Serving',
    icon: AiOutlineRobot,
    color: '#9333ea',
    category: 'aiml',
    description: 'ML model serving API',
  },
  featureStore: {
    id: 'featureStore',
    label: 'Feature Store',
    icon: MdDataUsage,
    color: '#9333ea',
    category: 'aiml',
    description: 'ML feature storage',
  },
  trainingPipeline: {
    id: 'trainingPipeline',
    label: 'Training Pipeline',
    icon: FiRefreshCw,
    color: '#9333ea',
    category: 'aiml',
    description: 'Model training workflow',
  },
  inferenceEngine: {
    id: 'inferenceEngine',
    label: 'Inference Engine',
    icon: BiChip,
    color: '#9333ea',
    category: 'aiml',
    description: 'Real-time ML inference',
  },
  mlflow: {
    id: 'mlflow',
    label: 'MLflow',
    icon: SiMlflow,
    color: '#0194e2',
    category: 'aiml',
    description: 'ML experiment tracking',
  },
  jupyter: {
    id: 'jupyter',
    label: 'Jupyter',
    icon: SiJupyter,
    color: '#f37726',
    category: 'aiml',
    description: 'Jupyter notebooks',
  },
  aiAssistant: {
    id: 'aiAssistant',
    label: 'AI Assistant',
    icon: AiOutlineRobot,
    color: '#9333ea',
    category: 'aiml',
    description: 'AI chatbot/assistant',
  },
  llm: {
    id: 'llm',
    label: 'LLM',
    icon: GiBrain,
    color: '#9333ea',
    category: 'aiml',
    description: 'Large Language Model',
  },
  vectorDB: {
    id: 'vectorDB',
    label: 'Vector DB',
    icon: BiData,
    color: '#9333ea',
    category: 'aiml',
    description: 'Vector database for embeddings',
  },
  embeddingService: {
    id: 'embeddingService',
    label: 'Embeddings',
    icon: MdMemory,
    color: '#9333ea',
    category: 'aiml',
    description: 'Text/image embedding service',
  },
  
  // Data Processing
  etl: {
    id: 'etl',
    label: 'ETL Pipeline',
    icon: BiData,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Extract Transform Load',
  },
  spark: {
    id: 'spark',
    label: 'Apache Spark',
    icon: SiApachespark,
    color: '#e25a1c',
    category: 'dataProcessing',
    description: 'Distributed data processing',
  },
  airflow: {
    id: 'airflow',
    label: 'Airflow',
    icon: SiApacheairflow,
    color: '#017cee',
    category: 'dataProcessing',
    description: 'Workflow orchestration',
  },
  dataLake: {
    id: 'dataLake',
    label: 'Data Lake',
    icon: FiDatabase,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Raw data storage',
  },
  streamProcessing: {
    id: 'streamProcessing',
    label: 'Stream Processing',
    icon: FiZap,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Real-time data streaming',
  },
  batchProcessing: {
    id: 'batchProcessing',
    label: 'Batch Processing',
    icon: FiRefreshCw,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Scheduled batch jobs',
  },
  dataIngestion: {
    id: 'dataIngestion',
    label: 'Data Ingestion',
    icon: FiDownloadCloud,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Data collection service',
  },
  dataTransform: {
    id: 'dataTransform',
    label: 'Data Transform',
    icon: FiCode,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Data transformation layer',
  },
  dataValidation: {
    id: 'dataValidation',
    label: 'Data Validation',
    icon: FiShield,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Data quality checks',
  },
  dataOrchestrator: {
    id: 'dataOrchestrator',
    label: 'Orchestrator',
    icon: BiLineChart,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Workflow management',
  },
  realtimeAnalytics: {
    id: 'realtimeAnalytics',
    label: 'Real-time Analytics',
    icon: MdAnalytics,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Live data analytics',
  },
  dataCatalog: {
    id: 'dataCatalog',
    label: 'Data Catalog',
    icon: FiDatabase,
    color: '#fb923c',
    category: 'dataProcessing',
    description: 'Data discovery & metadata',
  },
};

export const getNodesByCategory = (category) => {
  return Object.values(nodeTypes).filter((node) => node.category === category);
};

export const getAllNodes = () => {
  return Object.values(nodeTypes);
};
